name: pydeequ-test

channels:
  - anaconda

dependencies:
  - ipython
  - ipykernel
  - openjdk=11
  - findspark
  - pandas
  - pip
  - pip:
    - pydeequ
    - pyspark==3.0
    - s3fs 
    - fastparquet 
    - pyarrow